### ISSUE TITLE
design du personnage

### ISSUE THREAD

**Issue by sylvainpolletvillard** [clubgamedev/lost-chapters#1]
Yo,

Il ressemblerait à quoi le personnage du jeu ? Garçon, fille ? Quel âge, quel style ? Je voudrais bien bosser sur quelques protos bien dégueu en pixel art ^^ J'imagine faire 4 sprites pour les 4 directions

**Comment by sylvainpolletvillard** [comment]
premier essai pour roland banks, 

j'ai changé de technique (spray au lieu de crayon) pour m'entraîner et pour essayer de reproduire les plis de manteau et les ombrages. Mais le cuir c'est compliqué...
![image](https://user-images.githubusercontent.com/566536/47271101-44628f80-d575-11e8-8129-bf37c20791a0.png)

image d'origine:
![image](https://user-images.githubusercontent.com/566536/47271104-4cbaca80-d575-11e8-8be0-04b2794ad386.png)

**Comment by aneveux** [comment]
oh joli :)

**Comment by sylvainpolletvillard** [comment]
![michel](https://user-images.githubusercontent.com/566536/47616753-4f5f7780-dac1-11e8-81b4-4705fc78fd01.png)
![michelle](https://user-images.githubusercontent.com/566536/47616754-4f5f7780-dac1-11e8-81ee-fe07b05c5c46.png)

Voilà deux spritesheets pour les persos joueur, version homme et femme. Ils sont à la bonne taille par rapport à notre tiletset. J'ai repris le chapeau à ruban emblématique de Roland Banks

**Comment by aneveux** [comment]
Oh c'est excellent ça !

J'aime vraiment beaucoup ! Ca colle très bien au thème et je leur trouve un joli p'tit charme :)

Super boulot !

**Comment by sylvainpolletvillard** [comment]
Je les ai intégré au repo si tu veux voir les animations en action

**Comment by sylvainpolletvillard** [comment]
Hop 2 nouveaux persos, sans description visuelle je me suis basé sur mon imagination

Franck:
![franck](https://user-images.githubusercontent.com/566536/47683835-13b3d300-dbd1-11e8-9ae1-b1160a8a3277.png)

Augustin:
![augustin](https://user-images.githubusercontent.com/566536/47683836-13b3d300-dbd1-11e8-8152-267cec6139ef.png)

**Comment by aneveux** [comment]
:ok_hand: 

J'adore :)

**Comment by sylvainpolletvillard** [comment]
on va dire que c'est validé pour le perso principal. Les autres persos on en discute ici: https://github.com/clubgamedev/lost-chapters/issues/30
