### ISSUE TITLE
Ecran et son de victoire

### ISSUE THREAD

**Issue by benjamin-mailliet** [clubgamedev/lost-chapters#11]
Afficher un message et jouer un son pour indiquer que le joueur a bien déchiffrer la dernière rune avant de revenir au jeu principal.

**Comment by benjamin-mailliet** [comment]
Ecran fait et pushé, il ne manque plus que la petite musique qui va bien.

**Comment by sylvainpolletvillard** [comment]
ça a du sens de reprendre le même effet sonore pour la victoire/défaite de tous les mini jeux ?
