### ISSUE TITLE
choix de la police

### ISSUE THREAD

**Issue by sylvainpolletvillard** [clubgamedev/lost-chapters#3]
Qui dit jeu narratif dit beaucoup de texte, aussi il vaut mieux pas se planter sur le choix de la police.

Dans l'esprit pixel art et lovecraftien donc un peu gothique, je propose celle-ci: https://www.dafont.com/fr/alagard.font

![image](https://user-images.githubusercontent.com/566536/47747371-7fa54280-dc88-11e8-82cc-1643ac702e2e.png)

Il faudra juste ajouter manuellement les caractères accentués français à la font, un peu de boulot mais parfaitement abordable.

D'autres propositions ?

**Comment by aneveux** [comment]
Je veux bien un tuto pour modifier les fonts avec les accents :)

Mais en effet je la trouve très jolie !

**Comment by sylvainpolletvillard** [comment]
J'ai jamais fait, mais une recherche google "free font editor" et une soirée de libre devraient suffire je pense.

Par contre, vu ta propension à étaler l'histoire en roman, il est probable que cette police soit trop grosse ou pas assez lisible pour l'usage qu'on veut en faire. Ça marchera pour les titres, mais après il faudra des polices plus simples comme celle-ci https://www.dafont.com/fr/press-start-2p.font

**Comment by sylvainpolletvillard** [comment]
C'est parti pour une soirée de test de polices...
![chrome_2018-11-29_23-15-01](https://user-images.githubusercontent.com/566536/49255783-4dc10080-f42d-11e8-9c65-f2acae2f0f8a.png)
![chrome_2018-11-29_23-17-15](https://user-images.githubusercontent.com/566536/49255784-4dc10080-f42d-11e8-8ce0-3053fcd65c32.png)
![chrome_2018-11-29_23-17-54](https://user-images.githubusercontent.com/566536/49255785-4dc10080-f42d-11e8-8ec6-53767e9e2ff7.png)
![chrome_2018-11-29_23-18-31](https://user-images.githubusercontent.com/566536/49255786-4dc10080-f42d-11e8-8fd2-613a1dc9bbc1.png)
![chrome_2018-11-29_23-19-03](https://user-images.githubusercontent.com/566536/49255787-4e599700-f42d-11e8-8524-7268b9235a57.png)


Franchement, je trouve qu'Alagard (la dernière) reste le meilleur choix. J'ai juste viré l'ombre et changé un peu la couleur

**Comment by sylvainpolletvillard** [comment]
On reste sur Alagard
