### ISSUE TITLE
[Mini jeux] Decryptor

### ISSUE THREAD

**Issue by benjamin-mailliet** [clubgamedev/lost-chapters#8]
# Intégration du mini-jeu
Le jeu pourrait se lancer via les événements suivants :
- Une inscription incompréhensible a été trouvé par le personnage
- Une incantation doit être prononcée

# Bases du jeu :
- Une ligne de "runes" (d'autres éléments pourraient être utilisés) correspondant chacune à une touche de la manette / clavier (8 touches différentes - up, down, left, right, a, b, x, y)
- Une partie d'écran au dessus (indices) permettant de convertir chacun des éléments en touches de manette
- Faire la combinaison de touches dans l'ordre
		
# Contraintes :
- Temps limité pour faire la combinaison
- Aucune erreur autorisée

# Exemples de partie d'écran "indices"
- Liste d'éléments avec touche associée
- Liste de couleurs avec touche associée
- Eléments noyés dans plein d'autres éléments avec touche associée

# Exemples de "difficultés" :
- Les éléments clignotent (mémoire)
- Les éléments se déplacent (observation)
- Les éléments "changent" à chaque touche de la combinaison tapée (observation rapide)
- L'écran se brouille par intervalle à cause de la peur / folie (mémoire)
- L'écran se noirci par intervalle à cause des ténèbres (mémoire)
- L'écran clignote noir à cause d'une ampoule défaillante (mémoire)
- Ecrire up / down / left / right …. Plutôt qu'une icone (déduction)
- Gérer une action supplémentaire de manière périodique pour réafficher les infos (essuyer le front, taper sur la lampe torche, chasser des mouches / asticots…) (mémoire, skill)

# Fin du mini jeu
- Réussite : la suite d'éléments a été déchiffrée en touche de clavier
- Échec : le temps est dépassé ou le nombre d'erreurs acceptable a été dépassé

**Comment by sylvainpolletvillard** [comment]
Cool, ça a l'air ambitieux ! Comme il s'agit d'un mini jeu, ce que je te propose c'est que ce mini jeu se répète dans plusieurs niveaux mais à chaque fois avec une difficulté supplémentaire, comme ça le joueur s'approprie les règles peu à peu. Et ça te permet de commencer simple pour le dev.

**Comment by benjamin-mailliet** [comment]
Oui c'est bien le but : commencer simple.
J'ai juste listé toutes les différentes variantes pour les garder en tête (certaines ne seront peut être tout simplement pas viables).
Je prévois donc de commencer avec : 
- Les éléments sont simplement affichés au dessus ;
- Les éléments sont affichés au dessus au milieu d'autres éléments erronés ;
- Les éléments clignotent.

**Comment by benjamin-mailliet** [comment]
Le feeling de fin de jeu est pour le moment mauvais :
 - son coupé
 - écran qui fige avant le changement de scène

Donc RAF :
- Intégration d'un effet ou d'un écran de victoire avec une musique particulière
- Intégration d'un effet ou d'un écran de défait avec une musique particulière
- Amélioration du son de réussite pour qu'il soit de plus en plus "aigu" / "haut" (voir avec les zikos)
- Trouver ou construire un fond d'écran plus cool
